export type SearchState = {
    keyword: string,
    category: string, 
    city: string,
}

export type SearchBusState = {
    city: string,
    route: string,
}


export type ActivityState = {
    ID: string,
    Name: string,
    Description: string,
    Particpation?: string,
    Location: string,
    Address?: string,
    Phone?: string,
    Organizer?: string,
    StartTime?: string,
    EndTime?: string,
    Cycle?: string,
    NonCycle?: string,
    WebsiteUrl?: string,
    Picture?: any ,
    Position?: any,
    Class1?: string ,
    Class2?: string ,
    MapUrl?: string ,
    TravelInfo?: string ,
    ParkingInfo?: string ,
    Charge?: string ,
    Remarks?: string ,
    City?: string ,
    SrcUpdateTime?: any,
    UpdateTime?: any,
}

export type FoodState = {
    ID: string,
    Name: string ,
    Description?: string ,
    Address?: string ,
    ZipCode?: string ,
    Phone?: string ,
    OpenTime?: string ,
    WebsiteUrl?: string ,
    Picture?: any ,
    Position?: any ,
    Class?: string ,
    MapUrl?: string ,
    ParkingInfo?: string ,
    City?: string ,
    SrcUpdateTime?: any,
    UpdateTime?: any,
}

export type HotelState = {
    ID: string,
    Name: string ,
    Description?: string ,
    Grade?: string ,
    Address?: string ,
    ZipCode?: string ,
    Phone?: string ,
    Fax?: string ,
    WebsiteUrl?: string ,
    Picture?: any ,
    Position?: any,
    Class?: string ,
    MapUrl?: string ,
    Spec?: string ,
    ServiceInfo?: string ,
    ParkingInfo?: string ,
    City?: string ,
    SrcUpdateTime?: any,
    UpdateTime?: any,
}